apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: sales-api

          # 现在硬编码了 镜像的版本，后续肯定不能这样做的～需要找到方法，
          image: sales-api-image:1.0
          resources:
            requests:
              cpu: "1000m" # I need access to 1/2 core on the node.
            limits:
              cpu: "2000m" # Execute instructions 50ms/100ms on my 1 core.
